import * as generatedParser from './generatedParser.js'

interface IGeneratedParser {
	yy: any
	parse(input: string): any
}

/**
 * This is the parser generated by JISON.
 * We keep this private.
 */
const parser: IGeneratedParser = (<any>generatedParser).parser
parser.yy.Node = class {
	constructor(
		public readonly type: string,
		public readonly params: any[]
	) {
		params.forEach((param) => {
			if (param instanceof parser.yy.Node)
				(<any>this)[param.Type] = param
		})
	}
}

export function parse(input: string): any {
	return parser.parse(input)
}

